name: snake CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu_20:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc python3 python3-pip && pip3 install setuptools cython numpy
    - name: install
      run:  pip3 install --upgrade pip && pip3 install .
    - name: test
      run: buttery-eel --help
  ubuntu_22:
    name: ubuntu-22.04
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y zlib1g-dev gcc python3 python3-pip && pip3 install setuptools cython numpy
    - name: install
      run:  pip3 install --upgrade pip && pip3 install .
    - name: test
      run: buttery-eel --help

